### ISSUE TITLE
Model link methon was crashed.

### ISSUE THREAD

**Issue by nemuruibai** [etherealxx/batchlinks-webui#10]
![image](https://user-images.githubusercontent.com/39950653/223622609-b355a24e-d6ad-43d1-b0d3-02cf5e543bf1.png)

**Comment by etherealxx** [comment]
Wait, are you using this extension for windows?
Sorry, but the code hasn't been updated for windows. This project is mainly foxused on colab implementation. Other than that, might broke things. But thank you for reporting this. I'll fix this if i can

**Comment by etherealxx** [comment]
also i think the log file is cutted at the bottom?

**Comment by nemuruibai** [comment]
> Wait, are you using this extension for windows?
> Sorry, but the code hasn't been updated for windows. This project is mainly foxused on colab implementation. Other than that, might broke things. But thank you for reporting this. I'll fix this if i can

yeah.i use this for windows.
error code is winerror123
thanks for reply

**Comment by etherealxx** [comment]
> yeah.i use this for windows. error code is winerror123 thanks for reply

@nemuruibai Thank you for your bug report! I fixed it, but as of right now, you can only use gdown and curl on Windows. I will add aria2 and wget later if i have time 😉. [here's the bug fix](https://github.com/etherealxx/batchlinks-webui#latest-release-v210)

**Comment by etherealxx** [comment]
Hello @nemuruibai👋 i don't know if you still use this extension on your local installation, but i updated the extension! It now will works proprely with every download method. And some download speed improvement too! You can update it by going to the extension directory and use `git pull`, or maybe you can use the update extension button on the webui.

For every new feature i added: https://github.com/etherealxx/batchlinks-webui#release-v300
