### ISSUE TITLE
CivitAI direct link method: slow download speed

### ISSUE THREAD

**Issue by faisalhr1997** [etherealxx/batchlinks-webui#11]
![image](https://user-images.githubusercontent.com/97628039/223926778-dae8af6d-d3eb-4781-998d-b3509e5a2411.png)

**Comment by faisalhr1997** [comment]
taking forever to download from civitai

**Comment by faisalhr1997** [comment]
Naming is not the issue here . Download speed is slow from civitai.

**Comment by etherealxx** [comment]
> Naming is not the issue here . Download speed is slow from civitai.

no no, you don't get it. hear me out

links with `civitai.com/api/download/models` doesn't have a filename in it.

request module is needed to get the filename correctly from content-disposition

downloading the entire file is a must to get that

it's a waste of time when downloading an entire file just to get the filename, then redownloading it again

so i just used the downloaded file from request

**Comment by etherealxx** [comment]
I made this branch to (hopefully) fix that problem
```
!rm -rf /content/stable-diffusion-webui/extensions/batchlinks-webui
!git clone -b civitupgrade https://github.com/etherealxx/batchlinks-webui /content/stable-diffusion-webui/extensions/batchlinks-webui
```
this should use the default downloader instead of `requests` for downloading civit stuff.
i need to make sure this works first before merging with main.

**Comment by faisalhr1997** [comment]
https://colab.research.google.com/drive/1wEa-tS10h4LlDykd87TF5zzpXIIQoCmq#scrollTo=8Uvqba0yKW7U
This colabs download mechanism got the code you could reuse

**Comment by etherealxx** [comment]
> https://colab.research.google.com/drive/1wEa-tS10h4LlDykd87TF5zzpXIIQoCmq#scrollTo=8Uvqba0yKW7U This colabs download mechanism got the code you could reuse

<img src="https://user-images.githubusercontent.com/64251396/224010161-f116b2f1-fae1-407d-875f-c6607546aaab.png" alt="x" width="400"/>

mine is better coz it supports MEGA👀 (though for gdrive, i'll add it on the next update, it's complicated to implement that without bugs)
anyway, he's using direct download method, nothing special with it. It's literally the download method i use to download huggingface etc.
His code also can't differentiate `.safetensors` embedding/LoRA, his system is flawed

**Comment by etherealxx** [comment]
> Download speed is slow from civitai.

Hello @faisalhr1997👋 The update is now live! It upgrades the method used to download from civitai. Now you can use aria2 and enjoy the maximum downlad speed! (it also now support gdrive links!✨)

Release note (every new feature): https://github.com/etherealxx/batchlinks-webui#release-v301
