### ISSUE TITLE
additional network not working

### ISSUE THREAD

**Issue by 9zy04441** [etherealxx/batchlinks-webui#20]
No matter the hashtag it populates in the module lora folder and not the additional network folder. However when i use the other Civitai extension in gradio web diffusion it works fine and that LORA downloads in the additional network folder and allows for keywords to trigger it.

**Comment by etherealxx** [comment]
What link are you using? Civitai? can you give me the links?

**Comment by etherealxx** [comment]
@9zy04441 hello, can you please elaborate?
![2023-03-25 22_49_37-Stable Diffusion](https://user-images.githubusercontent.com/64251396/227729001-f14cac7e-462b-4641-b5b1-5a4ff9b5af30.png)

**Comment by falsonerd** [comment]
Make sure to "refresh" additional network or any other module after download, otherwise it won't show up.
