### ISSUE TITLE
Control the volume of the sound effect?

### ISSUE THREAD

**Issue by harrywang** [etherealxx/batchlinks-webui#25]
I really like the feature of the sound effect notification - but the default sound is quite loud ^_^ anyway, we can control that? Thanks!

**Comment by harrywang** [comment]
I got it, this file is played https://github.com/etherealxx/batchlinks-webui/blob/main/notification.mp3. I found another one https://cdn.pixabay.com/download/audio/2022/03/20/audio_25e43bb841.mp3?filename=music-box-98027.mp3 that I like better :) 

There are a lot options here: 

https://pixabay.com/sound-effects/search/notification/?manual_search=1&order=None

**Comment by etherealxx** [comment]
@harrywang sorry for late response, my pc was broken for a week. Anyway,

Yeah i noticed the sound is quite lound ans sometimes disturbing. Maybe i'll decrease the volume of it. For your other option though, that music box one is kinda nice. But how about the license?

The one i use is cc0 so i can just download it and redistribute without crediting.

**Comment by harrywang** [comment]
its royalty free：https://pixabay.com/service/license-summary/

**Comment by etherealxx** [comment]
sorry for late late response. i ended up using [this](https://pixabay.com/sound-effects/short-success-sound-glockenspiel-treasure-video-game-6346/).
again, thank you so much for your feedback.✨

**Comment by harrywang** [comment]
> sorry for late late response. i ended up using [this](https://pixabay.com/sound-effects/short-success-sound-glockenspiel-treasure-video-game-6346/).
> 
> again, thank you so much for your feedback.✨

great choice！ 😆
