### ISSUE TITLE
Feature Suggestion and Testing

### ISSUE THREAD

**Issue by NUROISEA** [etherealxx/batchlinks-webui#4]
A lot of embeddings and loras are uploaded to catbox.moe and related sites from users on 4ch.

Maybe an edge case, I tend to store my TIs in Discord since its quite convenient.

Since this extension is already utilizing `gdown`, downloading from Google Drive also?

Maybe add this as a toggleable option since supporting every site will lead to unexpected things.

**Comment by etherealxx** [comment]
The thing is, sometimes gdown fails to download from google drive, idk why. Weird.
![image](https://user-images.githubusercontent.com/64251396/220621896-4423187a-b3cd-4f6f-ab5c-788ed861aad9.png)
Something like this. Even though the link is public.

I'll try to add the other websites. You can list the most used website for these.

Catbox is banned in my country, i'll figure things out.

**Comment by etherealxx** [comment]
for discord is it this link? https://cdn.discordapp.com/attachments/*

**Comment by NUROISEA** [comment]
> The thing is, sometimes gdown fails to download from google drive, idk why. Weird.

Heavily guessing here, but maybe the file has a delay on being updated to the servers?

> Catbox is banned in my country, i'll figure things out.

Even if catbox is banned in your country, pretty sure that Google's servers are in not in the countries that have strict internet censorship. IIRC, the servers are in US, EU, and SG. catbox links are `wget`-able and will most likely work with any CLI downloader.

> for discord is it this link? https://cdn.discordapp.com/attachments/*

Yes it is! 
![image](https://user-images.githubusercontent.com/120075289/220643328-06624be7-72ba-4d4b-8290-8cbc81d8669d.png)

> I'll try to add the other websites. You can list the most used website for these.

I think having a special case for websites would be a bad idea and will lead to code bloat, I propose that having a toggle of downloading from anywhere would faster to implement (also easier?).

But regardless, these are the sites that provide direct links to files that I can list at the top of my head:
 - `*.s-ul.eu/*`
 - `github.com/*/*/raw/*/*` or `raw.githubusercontent.com/*/*/*`
 - `cdn.discordapp.com/attachments/*/*/*`
 - `files.catbox.moe/*`
 - `gitgud.io/*/*/-/raw/*/*`

**Comment by etherealxx** [comment]
> pretty sure that Google's servers are in not in the countries that have strict internet censorship. IIRC, the servers are in US, EU, and SG. catbox links are wget-able and will most likely work with any CLI downloader.

wget etc. doesn't work on catbox even on colab, i tried. Maybe i'll try again with vpn.

**Comment by NUROISEA** [comment]
> > pretty sure that Google's servers are in not in the countries that have strict internet censorship. IIRC, the servers are in US, EU, and SG. catbox links are wget-able and will most likely work with any CLI downloader.
> 
> wget etc. doesn't work on catbox even on colab, i tried. Maybe i'll try again with vpn.

Can confirm, catbox does not work. It's just stuck in an eternal halt.
![image](https://user-images.githubusercontent.com/120075289/220657720-b4ac4ed7-ef33-42fa-ab5c-3654766752bd.png)

Apologies, I must've jumbled up my memory 😅

**Comment by etherealxx** [comment]
@NUROISEA try this branch
```
!git clone -b ariasubprocess https://github.com/etherealxx/batchlinks-webui /content/stable-diffusion-webui/extensions/batchlinks-webui
```
i added aria2 downloader, discord attachment, changed os.system to subprocess, more accurate logging system, controlnet path, and github extension clone. I'll merge to main if it's stable enough.

Still uncertain about the other websites. Maybe you can give me model link examples for every website?😊

Imma sleep for now. It's midnight on my timezone🌃

**Comment by NUROISEA** [comment]
Did a quick test. It seems like the downloaded files are not being placed to their respective folders.
![image](https://user-images.githubusercontent.com/120075289/220817118-e803d96b-a471-49f1-8bb1-33214da282ef.png)


This is my input:
```txt
#embed
https://cdn.discordapp.com/attachments/1064919066420203551/1064919069519773757/EMT.pt
https://cdn.discordapp.com/attachments/1066570375653244928/1066570434746785882/Moomers.pt
#hypernet
https://cdn.discordapp.com/attachments/1070489470127841381/1070489471964954684/MomopocoV3.pt
https://github.com/fkunn1326/openpose-editor
```

UI Output:
![image](https://user-images.githubusercontent.com/120075289/220817261-e9bc4b7c-7f1d-4b54-83ef-e0d9682767a1.png)

<details>
<summary>Console output:</summary>

```
BatchLinks Downloads starting...


https://cdn.discordapp.com/attachments/1064919066420203551/1064919069519773757/EMT.pt
Installing aria2 ...

Selecting previously unselected package libc-ares2:amd64.
(Reading database ... 128126 files and directories currently installed.)
Preparing to unpack .../libc-ares2_1.15.0-1ubuntu0.1_amd64.deb ...
Unpacking libc-ares2:amd64 (1.15.0-1ubuntu0.1) ...
Selecting previously unselected package libaria2-0:amd64.
Preparing to unpack .../libaria2-0_1.35.0-1build1_amd64.deb ...
Unpacking libaria2-0:amd64 (1.35.0-1build1) ...
Selecting previously unselected package aria2.
Preparing to unpack .../aria2_1.35.0-1build1_amd64.deb ...
Unpacking aria2 (1.35.0-1build1) ...
Setting up libc-ares2:amd64 (1.15.0-1ubuntu0.1) ...
Setting up libaria2-0:amd64 (1.35.0-1build1) ...
Setting up aria2 (1.35.0-1build1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
aria2 installed!

02/23 03:43:08 [NOTICE] Download complete: -o EMT.pt/EMT.pt

02/23 03:43:08 [INFO] The segment file -o EMT.pt/EMT.pt.aria2 exists.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
fee07e|OK  |   5.0MiB/s|-o EMT.pt/EMT.pt

Status Legend:
(OK):download completed.

https://cdn.discordapp.com/attachments/1066570375653244928/1066570434746785882/Moomers.pt
02/23 03:43:09 [NOTICE] Download complete: -o Moomers.pt/Moomers.pt

02/23 03:43:09 [INFO] The segment file -o Moomers.pt/Moomers.pt.aria2 exists.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
b38a9e|OK  |   6.0MiB/s|-o Moomers.pt/Moomers.pt

Status Legend:
(OK):download completed.

https://cdn.discordapp.com/attachments/1070489470127841381/1070489471964954684/MomopocoV3.pt
02/23 03:43:11 [NOTICE] Download complete: -o MomopocoV3.pt/MomopocoV3.pt

02/23 03:43:11 [INFO] The segment file -o MomopocoV3.pt/MomopocoV3.pt.aria2 exists.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
be529c|OK  |    81MiB/s|-o MomopocoV3.pt/MomopocoV3.pt

Status Legend:
(OK):download completed.

https://github.com/fkunn1326/openpose-editor
Cloning into '/content/stable-diffusion-webui/extensions/openpose-editor'...
remote: Enumerating objects: 141, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 141 (delta 13), reused 20 (delta 12), pack-reused 116
Receiving objects: 100% (141/141), 919.64 KiB | 3.27 MiB/s, done.
Resolving deltas: 100% (51/51), done.

BatchLinks Downloads finished!
```

</details>

**Comment by NUROISEA** [comment]
`gdown` test, same inputs, download fails

UI output:
![image](https://user-images.githubusercontent.com/120075289/220817991-b44659e6-b1d0-4b65-81ea-bd791af95d34.png)

<details><summary>Console output</summary>

```
BatchLinks Downloads starting...


https://cdn.discordapp.com/attachments/1064919066420203551/1064919069519773757/EMT.pt
usage: gdown
       [-h]
       [-V]
       [-O OUTPUT]
       [-q]
       [--fuzzy]
       [--id]
       [--proxy PROXY]
       [--speed SPEED]
       [--no-cookies]
       [--no-check-certificate]
       [--continue]
       [--folder]
       [--remaining-ok]
       url_or_id
gdown: error: argument -O/--output: expected one argument

https://cdn.discordapp.com/attachments/1066570375653244928/1066570434746785882/Moomers.pt
usage: gdown
       [-h]
       [-V]
       [-O OUTPUT]
       [-q]
       [--fuzzy]
       [--id]
       [--proxy PROXY]
       [--speed SPEED]
       [--no-cookies]
       [--no-check-certificate]
       [--continue]
       [--folder]
       [--remaining-ok]
       url_or_id
gdown: error: argument -O/--output: expected one argument

https://cdn.discordapp.com/attachments/1070489470127841381/1070489471964954684/MomopocoV3.pt
usage: gdown
       [-h]
       [-V]
       [-O OUTPUT]
       [-q]
       [--fuzzy]
       [--id]
       [--proxy PROXY]
       [--speed SPEED]
       [--no-cookies]
       [--no-check-certificate]
       [--continue]
       [--folder]
       [--remaining-ok]
       url_or_id
gdown: error: argument -O/--output: expected one argument

https://github.com/fkunn1326/openpose-editor
fatal: destination path '/content/stable-diffusion-webui/extensions/openpose-editor' already exists and is not an empty directory.

BatchLinks Downloads finished!
```

</details>

**Comment by NUROISEA** [comment]
`wget` test, same inputs (only removed github link), download fails

UI output:
![image](https://user-images.githubusercontent.com/120075289/220818312-df1239a1-b36f-4199-9e00-359f9f80d89a.png)

<details><summary>Console output</summary>

```
BatchLinks Downloads starting...


https://cdn.discordapp.com/attachments/1064919066420203551/1064919069519773757/EMT.pt
wget: option requires an argument -- 'P'
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.

https://cdn.discordapp.com/attachments/1066570375653244928/1066570434746785882/Moomers.pt
wget: option requires an argument -- 'P'
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.

https://cdn.discordapp.com/attachments/1070489470127841381/1070489471964954684/MomopocoV3.pt
wget: option requires an argument -- 'P'
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.

BatchLinks Downloads finished!
```

</details>

**Comment by NUROISEA** [comment]
`curl` test, same inputs (no github), downloads correctly

UI output:
![image](https://user-images.githubusercontent.com/120075289/220818504-b2640323-65c9-4f6a-a85a-64f8bdf2d609.png)



<details><summary>Console output</summary>

```
BatchLinks Downloads starting...


https://cdn.discordapp.com/attachments/1064919066420203551/1064919069519773757/EMT.pt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26727  100 26727    0     0   450k      0 --:--:-- --:--:-- --:--:--  457k

https://cdn.discordapp.com/attachments/1066570375653244928/1066570434746785882/Moomers.pt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 31659  100 31659    0     0   533k      0 --:--:-- --:--:-- --:--:--  533k

https://cdn.discordapp.com/attachments/1070489470127841381/1070489471964954684/MomopocoV3.pt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 83.8M  100 83.8M    0     0   190M      0 --:--:-- --:--:-- --:--:--  189M

BatchLinks Downloads finished!
```

</details>

**Comment by etherealxx** [comment]
Sorry, i think the extension update breaks everything. You can git checkout to the previous commit (on the same branch). I'm currently not in my house, I'll check that later.

**Comment by etherealxx** [comment]
Try this one
```
!rm -rf /content/stable-diffusion-webui/extensions/batchlinks-webui
!git clone https://github.com/etherealxx/batchlinks-webui /content/stable-diffusion-webui/extensions/batchlinks-webui
!cd /content/stable-diffusion-webui/extensions/batchlinks-webui
!git checkout ariasubprocess
!git checkout 0e0c37844eef9be0be91d5dddba758c94931005e
```

**Comment by etherealxx** [comment]
@NUROISEA whoops sorry, wrong command. Here's the one:
```
!rm -rf /content/stable-diffusion-webui/extensions/batchlinks-webui
!git clone -b ariasubprocess https://github.com/etherealxx/batchlinks-webui /content/stable-diffusion-webui/extensions/batchlinks-webui
%cd /content/stable-diffusion-webui/extensions/batchlinks-webui
!git checkout 0e0c37844eef9be0be91d5dddba758c94931005e .
```

**Comment by etherealxx** [comment]
okay, i noticed the same problem also happens on that commit. I know the problem and will fix it soon

**Comment by etherealxx** [comment]
@NUROISEA sorry for the inconvenience🙏, i pushed a new commit.
```
!rm -rf /content/stable-diffusion-webui/extensions/batchlinks-webui
!git clone -b ariasubprocess https://github.com/etherealxx/batchlinks-webui /content/stable-diffusion-webui/extensions/batchlinks-webui
```
It fixes most of the bugs, all downloader working, extension texted, haven't tested discord attachment yet. Thank you by the way, for debugging my previous code, really appreciated😁✨

Currently i'm planning to update it once more before merging to main. Someone give me codes to directly download from civitai model page link, instead of from civitai direct link.😊

**Comment by NUROISEA** [comment]
Hi @etherealxx, I tested your branch against the [latest version](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8) of the webui and against [my fork](https://github.com/NUROISEA/stable-diffusion-webui/tree/23.02.04) (previous versions of the webui) and I saw no problems with your extension!

Test case:
```
#model
https://huggingface.co/NoCrypt/SomethingV2/resolve/main/somethingv2_1.safetensors
#vae
https://huggingface.co/NUROISEA/av3-mirror/resolve/main/anything.vae.pt
#embed
https://cdn.discordapp.com/attachments/1064919066420203551/1064919069519773757/EMT.pt
https://cdn.discordapp.com/attachments/1066570375653244928/1066570434746785882/Moomers.pt
#hypernet
https://cdn.discordapp.com/attachments/1070489470127841381/1070489471964954684/MomopocoV3.pt
#lora
https://huggingface.co/YoungMasterFromSect/Trauter_LoRAs/resolve/main/LoRA/Misc.%20Characters/Aponia/Aponia_Softpruned.safetensors
https://github.com/fkunn1326/openpose-editor
```

Tested with all 4 download methods `gdown`, `wget`, `curl`, `aria2` with both versions of the web ui and it works as expected.

Test environment (a colab I quickly wrote for this purpose)
![image](https://user-images.githubusercontent.com/120075289/220911602-d9b38b9e-3c60-4536-a91c-96f3c2cb9981.png)

Output:
![image](https://user-images.githubusercontent.com/120075289/220912077-502204cf-2fd0-43e9-9f19-589ff82b1103.png)


Test limitations:
 - did not try mega (I don't have any embeds or loras easily available)
 - did not try civitai

**Comment by etherealxx** [comment]
Thank you!😊✨
MEGA is working fine, so does Civitai.
However, a friend of mine implemented a new way to download Civitai stuff using the api. So instead of using the direct download link (example, https://civitai.com/api/download/models/5616), it uses the model page link, (example, https://civitai.com/models/4823/deliberate), and it will automatically download the best model, download the thumbnail, and put it as as a preview image on webui. Also, it automatically knows the type of the model (it will be located properly automatically without using hashtag thing). If that works perfectly, then sd-civitai-browser would be kinda useless😅

So i'll try to implement that on the next commit.

Also that person commented about the UI. I wanna hear from you what do you think about the UI honestly. I try to make it as easy-for-beginner as possible (as i was months ago).

**Comment by NUROISEA** [comment]
> So i'll try to implement that on the next commit.

Yo, let's go!

> I wanna hear from you what do you think about the UI honestly. I try to make it as easy-for-beginner as possible

The UI is intuitive, at a glance you kinda know what you are dealing with already, so no problems on the UI side of things. :D

**Comment by etherealxx** [comment]
hello @NUROISEA 👋

After hours of staring at codes, finally i pushed this (almost) final commit. Here's the list of [all new features](https://github.com/etherealxx/batchlinks-webui/tree/ariasubnewcivit#latest-release-v200.)

you can test it with this:
```
!git clone -b ariasubnewcivit https://github.com/etherealxx/batchlinks-webui /content/stable-diffusion-webui/extensions/batchlinks-webui
```

i tested most of it works (haven't tested Windows yet). If it's stable enough, i'll merge it with main. (I'll also ask some of my friend on discord to test it too i think)😊

**Comment by NUROISEA** [comment]
Hi @etherealxx! here's my testing:

<details><summary>Inputs:</summary>

```text
#model
https://huggingface.co/swl-models/mix-pro-v3/resolve/main/mix-pro-v3-non-ema-fp16.safetensors
#vae
https://huggingface.co/NUROISEA/av3-mirror/resolve/main/anything.vae.pt
#embed
https://cdn.discordapp.com/attachments/1064919066420203551/1064919069519773757/EMT.pt
https://cdn.discordapp.com/attachments/1066570375653244928/1066570434746785882/Moomers.pt
#hypernet
https://cdn.discordapp.com/attachments/1070489470127841381/1070489471964954684/MomopocoV3.pt
#lora
https://huggingface.co/YoungMasterFromSect/Trauter_LoRAs/resolve/main/LoRA/Misc.%20Characters/Aponia/Aponia_Softpruned.safetensors
https://mega.nz/file/gAxTWBAI#uL7EZay-OND5G6ELJlGfUNG0s7Q4TynZKqFdvs0v0tc ##agent8-finetune
https://mega.nz/file/oU43FSTY#vwAfsAb7RKJ4xtsSP7uzrKpWhh1y8BdpIBFurwsVP2o ##agent8-dreambooth

https://github.com/fkunn1326/openpose-editor
https://civitai.com/models/7448/korean-doll-likeness
```

</details>

Results:
Tested on the [latest version](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8) of the webui and a [slightly older one](https://github.com/NUROISEA/stable-diffusion-webui/tree/23.02.04)
|     | `gdown` | `wget` | `curl` | `aria2` | 
| --- | :---:     | :---: | :---: | :---: |
| huggingface | ✅ | ✅ | ✅ | ✅ |
| civitai | ✅ | ✅ | ✅ | ❌ |
| discord | ✅ | ✅ | ✅ | ✅ |
| mega |  ✅ | ✅ | ✅ | ✅ |
| github |  ✅ | ✅ | ✅ | ✅ |

Civitai seems to fail on both methods on aria2, direct `/api/models/` and `/models/`, error seems to be the same to both instances:

<details><summary>Civitai error log:</summary>

```text
https://civitai.com/models/7448/korean-doll-likeness
debug download_url(https://civitai.com/api/download/models/14014, /content/stable-diffusion-webui/models/Lora/koreanDollLikeness_v15.safetensors, aria2)
debug new_command_parts: ['aria2c', '--console-log-level=info', '-c', '-x', '16', '-s', '16', '-k', '1M', 'https://civitai.com/api/download/models/14014', '-d', '/content/stable-diffusion-webui/models/Lora', '-o', 'koreanDollLikeness_v15.safetensors']
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/stable-diffusion-webui/extensions/batchlinks-webui/scripts/batchlinks-downloader.py", line 700, in run
    civitdown2(currentlink, currentfolder, choosedowner)
  File "/content/stable-diffusion-webui/extensions/batchlinks-webui/scripts/batchlinks-downloader.py", line 514, in civitdown2
    hfdown(data_url, data_save_path, downloader, True)
  File "/content/stable-diffusion-webui/extensions/batchlinks-webui/scripts/batchlinks-downloader.py", line 567, in hfdown
    runwithsubprocess(f"aria2c --console-log-level=info -c -x 16 -s 16 -k 1M {todownload_s} -d {folder_s} -o {filename}", folder_s)
  File "/content/stable-diffusion-webui/extensions/batchlinks-webui/scripts/batchlinks-downloader.py", line 244, in runwithsubprocess
    print("debug folderforsavestate: " + folder)
TypeError: can only concatenate str (not "PosixPath") to str
```

</details>

Another bug I saw is the output box seems to not display anything after finishing the task, successful or not. Granted, I am not using `--gradio-queue` in my tests.

**Comment by etherealxx** [comment]
> Hi @etherealxx! here's my testing:

Thank you so much for the findings!🤗✨

that error log is actually comes from the debug text i made for, well, debugging purposes.
```
    print("debug folderforsavestate: " + folder)
TypeError: can only concatenate str (not "PosixPath") to str
```
should be like this
```
print("debug folderforsavestate: " + str(folder))
```

Also yeah, i haven't tested this on non queue environment and the old version, i might check that. More bug fixing to come🛠️🪲🏃‍♂️💨💨

**Comment by etherealxx** [comment]
hi @NUROISEA , it's been a while😅
I did more fixing and adding stuff. I'm hoping that this is the last update before i merge to main.😁 Here's [all the new features](https://github.com/etherealxx/batchlinks-webui/tree/ariasubnewcivit#latest-release-v200). (and yes, github raw and catbox is supported)
```
!git clone -b ariasubnewcivit https://github.com/etherealxx/batchlinks-webui /content/stable-diffusion-webui/extensions/batchlinks-webui
```
I tested it on camenduru's v2.0. Also with gradio queue on, as queue off might breaks some things. (camen's colab is queue on by default anyway)

I also has this version that was built solely for camenduru's v1.6 colab. (won't work properly on others)
```
!git clone -b onedotsix https://github.com/etherealxx/batchlinks-webui /content/stable-diffusion-webui/extensions/batchlinks-webui
```
> Another bug I saw is the output box seems to not display anything after finishing the task, successful or not.

this one seems to be an issue with timeout and websocket (i didn't quite understand that), but to mitigate that problem, this 'onedotsix' variant will cut the download session every 2 minutes, and there will be a resume button to resume the cutted download session.

**Comment by NUROISEA** [comment]
Hi hello @etherealxx o/

I'm quite short in time so I only tested your extension on a [1 month old commit of the webui](https://github.com/NUROISEA/stable-diffusion-webui/tree/23.02.04) since I figured there's no major changes between this and the latest version of the webui anyway 😄

Alas the test went smooth, no problems whatsoever!

Tested with `--gradio-queue`

<details><summary>Input</summary>

```
#model
https://huggingface.co/swl-models/mix-pro-v3/resolve/main/mix-pro-v3-non-ema-fp16.safetensors
#vae
https://huggingface.co/NUROISEA/av3-mirror/resolve/main/anything.vae.pt
#embed
https://cdn.discordapp.com/attachments/1064919066420203551/1064919069519773757/EMT.pt
https://cdn.discordapp.com/attachments/1066570375653244928/1066570434746785882/Moomers.pt
#hypernet
https://cdn.discordapp.com/attachments/1070489470127841381/1070489471964954684/MomopocoV3.pt
#lora
https://huggingface.co/YoungMasterFromSect/Trauter_LoRAs/resolve/main/LoRA/Misc.%20Characters/Aponia/Aponia_Softpruned.safetensors
https://mega.nz/file/gAxTWBAI#uL7EZay-OND5G6ELJlGfUNG0s7Q4TynZKqFdvs0v0tc ##agent8-finetune
https://mega.nz/file/oU43FSTY#vwAfsAb7RKJ4xtsSP7uzrKpWhh1y8BdpIBFurwsVP2o ##agent8-dreambooth
https://files.catbox.moe/48tq2i.safetensors ##gawr gura atlantis
https://files.catbox.moe/uarze8.safetensors ##neurosama!
https://github.com/fkunn1326/openpose-editor
https://civitai.com/models/5373/makima-chainsaw-man-lora ##lora
https://civitai.com/models/4379/toru8p-waven-chibi-style ##hypernetwork
https://civitai.com/models/3036/charturner-character-turnaround-helper-for-15-and-21 ##ti
```

</details>

All links work **on all download methods**, even catbox! 

Test limitation is I didn't test the raw github links since I cannot find TIs or anything that is hosted in github.

----

Since stuff works flawlessly, I'll just suggest things. These can be done on a later date, whenever you feel like it 😆

 - You can maybe change this so people know they can use catbox links
![image](https://user-images.githubusercontent.com/120075289/222128055-6b979760-664f-4ceb-a7a5-13d2f815f0e1.png)

 - The UI gets very squished on mobile phone resolutions.
![image](https://user-images.githubusercontent.com/120075289/222129190-279c89cc-aeb0-4352-9ecc-2867bf18c3db.png)



 - Catbox downloads files that have gibberish file names (the same as in the URL), maybe utilize the `##` comments to it? An idea:
```
#lora
https://files.catbox.moe/uarze8.safetensors ##r neurosama
```
Notice the `##r`, this would be downloaded as `neurosama.safetensors` instead of `uarze8.safetensors`. This is not an elegant approach, but I'm pretty sure that you can do something better.

 - Google drive support? This could be a higher priority since a lot of people use drive to store models since not everyone can use HuggingFace.

----

You did well on this 👏👏👏

I added your extension earlier on my colab collection, so kinda so it's being battle tested right now 😄

**Comment by etherealxx** [comment]
> Alas the test went smooth, no problems whatsoever!

Thank you! Since this is stable enough, i'll do some tweak then push straight away! (it's been pain in the ass holding the update long enough😅) Then i'll start adding more features.

> You can maybe change this so people know they can use catbox links

Will do! forgot about that😅

> The UI gets very squished on mobile phone resolutions.

This one is kinda hard. If i remove the `drop file here` on the right, the UI would look really ugly on my ultrawide monitor😅. But yeah, it would help mobile user. I'll try to improve the UI after the v2.0.0

> Catbox downloads files that have gibberish file names (the same as in the URL), maybe utilize the ## comments to it? An idea:

While i really like customization, it might get more confusing, as this hashtag syntaxing thing is, while designed to be really beginner friendly, i can see some people still getting confused to it. I would, figure out some stuff to allow easier way to renaming things.

> Google drive support? This could be a higher priority since a lot of people use drive to store models since not everyone can use HuggingFace.

Let's say it's complicated right now ([#43](https://github.com/wkentaro/gdown/issues/43) [#26](https://github.com/wkentaro/gdown/issues/26) [#146](https://github.com/wkentaro/gdown/issues/146)). Again, I'll add it if i figured things out.

> You did well on this 👏👏👏

Lastly, thank you so much 🙏✨ Couldn't thank you enough.

**Comment by etherealxx** [comment]
Hello @NUROISEA , long time no see😊

For the past couple weeks i've been developing on the next update of this extension. Some of the feature are the one that you requested: renaming and google drive support.

In fact, the rename function already available since weeks ago i think😅
works something like this:
```
#lora
https://files.catbox.moe/uarze8.safetensors > neurosama.safetensors
```
for current version that i'm developing, it's aiming to support more and more website. Currently:
![image](https://user-images.githubusercontent.com/64251396/225476370-91526c5c-c2d5-4065-a993-fbdd72d04f8d.png)

This update will also use different method for downloading civitai from direct links, speeding up the download speed by up to 40x (looks comical but the current method can sometimes goes really slow like 5Mbps). Also there's a lot going on in the backround, related to how civitai model page link is downloaded (takes a lot of my time to fix it 🙃)

Another feature i'm implementing is called 'sdless', where you can run the extension without even launching the sd-webui ([more here](https://github.com/etherealxx/batchlinks-webui/tree/sdless#sdless-mode)). It makes my developing progress much quicker! (though, this is the toughest update since i'm still learning things 😅)

Next feature that someone suggested is custom hashtag with custom path. Works something like this
```
@new #temp /content/temp
#temp
<link>
```

Another qol feature is `@extract` to extract every 7z file on curent directory.

Lastly, the UI got updated a bit, and that's it.

if you want to test it:
```
!git clone -b sdless https://github.com/etherealxx/batchlinks-webui /content/stable-diffusion-webui/extensions/batchlinks-webui
```
I might spend another day or two to write some stuff on the readme page, and then release the update straight away.

I would like to reach you in discord (etherealxx#7060) if you have one, so we can talk or something👀. Or maybe just join camenduru's server since i'm there too.✨

**Comment by NUROISEA** [comment]
Hi @etherealxx! Cool update!

I have tested the extension with the [latest A1111 commit](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a9fed7c364061ae6efb37f797b6b522cb3cf7aa2) with the same text file as my previous comments and there are some bugs, unfortunately:

 - Progress bar seems to be stuck to -1.0% if the download fails, but if the next download runs, the progress bar would function normally (this is quite inconsistent to happen)
 - ![image](https://user-images.githubusercontent.com/120075289/225630536-97e3838a-4b89-4970-96c4-75d12a3e6656.png)
 
- The progress bar doesn't have any indication? the bar colors, the text percentage seems to work as intended.
 - ![image](https://user-images.githubusercontent.com/120075289/225632018-16ff14cd-24b3-481e-bab8-4c513f0f20b8.png)

 - Is this intentional? The progress bar appears on the hashtags table:
 - ![image](https://user-images.githubusercontent.com/120075289/225630290-198e1eee-c931-47ed-8833-5a2689e84ff6.png)

Do note that my test is limited since I have limited time and do not have the proper links to the new sites but I would assume that they work, catbox in an exception since I am getting unlucky with the servers and I cannot download from that site. This is it for my bug reports. (sorry if this feels quite lazy I'm also doing something and I'm just testing on my downtime 😅)

----

I tried breaking your extension, by mixing up the hashtags, a simplified example would be:
```
#lora
<link>
#model
<link>
#lora
<link>
...
```
and it would just download it correctly to the appropriate places!

The rename feature is such a nifty QoL one, thank you for that. The custom path works as intended too!

I haven't tested `@extract` and I assume it only works with `.7z`?

I like what you have done to the UI, hiding stuff and stretching the UI seems pretty nifty (although stretched looks dank on wide resolutions 😂)

Overall, good job on this one! Seems pretty solid by the looks of it! 🎉

And yes I do have discord, I'll just DM you with this screenshot of this response in the editor. I think you can verify if you try to edit this.

**Comment by etherealxx** [comment]
Okay, time to address the problem.

> Progress bar seems to be stuck to -1.0% if the download fails

i don't know how to replicate it, honestly. Can you give me the example/links where it happens?
all i know for 1% is, i put that as placeholder to trigger the progressbar to run (idk but at one point the progress bar wont show up without that placeholder). I think i'll make sure the progress bar goes to 100% whenever the download is complete.

> The progress bar doesn't have any indication? the bar colors

It's supposed to be orange, gradio's color. But i think the auto1111's code messed it up. When i launch the UI standalone-ly, the progress bar works fine.

> Is this intentional? The progress bar appears on the hashtags table:

so the thing is, the way gradio works is an UI change only could happen by a return value passed into the components. I want it so that after the download is finished, the table become automatically updated, so that when ppl use custom hashtag, it will shows after the download is finished right away. (i can't update the UI while the code is running, unless it use `gradio every` like the log text, which blinks every now and then).
In order to update the table right after the download is complete, i need to assign the table as the output for the button, just like the output box. But how the progress bar works in gradio is, it will make every output as a progress bar, hence the table also appears as progress bar. (sucks honestly, but i can't find a good workaround currently)

> Do note that my test is limited since I have limited time and do not have the proper links to the new sites but I would assume that they work

I do test all of them, but you seem have a skill to somehow breaks my extension sometimes, and that's useful😆

> sorry if this feels quite lazy I'm also doing something and I'm just testing on my downtime 😅

Don't worry! I'm not forcing you at all. I'm just asking for a little help in your spare time😋 don't feel burdened, consider it a little activity when there is nothing to do.

> I haven't tested @extract and I assume it only works with .7z?

yeah i made it bcoz one of the link i downloaded from pixeldrain is a .7z file. Would be very handy coz the syntax for extracting a simple single item is pretty long. I'll add .zip and .rar support too i guess...

> I like what you have done to the UI, hiding stuff and stretching the UI seems pretty nifty (although stretched looks dank on wide resolutions 😂)

The reason i haven't got rid that useless huge `drop your txt here` on the old version is because, just like you said, it looks jank on my ultrawide monitor. So i instead add it as an option. The strech UI thing works great on mobile. Unstretched is the default, as it's how the UI looks like before.

Again, thank you for spending your time on this passion project of mine, really really appreciated😊
