### ISSUE TITLE
huggingface download finished but the downloaded files are small

### ISSUE THREAD

**Issue by harrywang** [etherealxx/batchlinks-webui#46]
https://huggingface.co/XpucT/Deliberate/blob/main/Deliberate_v2.safetensors

<img width="1272" alt="Screenshot 2024-02-09 at 1 59 02 PM" src="https://github.com/etherealxx/batchlinks-webui/assets/595772/d112cadc-9a51-41aa-825c-65a1d1462d44">

the file is downloaded quickly but it's not the full file.

**Comment by etherealxx** [comment]
you're copying the wrong link. this is the correct link
https://huggingface.co/XpucT/Deliberate/resolve/main/Deliberate_v2.safetensors

it has `resolve` on the link, not `blob`

get it by right clicking this then copy link
![image](https://github.com/etherealxx/batchlinks-webui/assets/64251396/47495685-5ed7-41ee-af6f-3bceb680474b)

**Comment by harrywang** [comment]
thank!
