### ISSUE TITLE
maybe take some inspiration from here

### ISSUE THREAD

**Issue by faisalhr1997** [etherealxx/batchlinks-webui#6]
https://github.com/aka7774/sd_filer

**Comment by faisalhr1997** [comment]
aria2 with multiple connection support

**Comment by etherealxx** [comment]
> aria2 with multiple connection support to speed up download to 10s per model

currently working on [this branch](https://github.com/etherealxx/batchlinks-webui/tree/ariasubprocess). I'll merge it to main after adding more features.

**Comment by etherealxx** [comment]
anyway, what does that extension (sd_filer) do?🤔

**Comment by faisalhr1997** [comment]
try out for yourself

**Comment by etherealxx** [comment]
hello sir 👋

I pushed a new update to a branch. Here's the list of [all new features](https://github.com/etherealxx/batchlinks-webui/tree/ariasubnewcivit#latest-release-v200.)

you can test it with this:
```
!git clone -b ariasubnewcivit https://github.com/etherealxx/batchlinks-webui /content/stable-diffusion-webui/extensions/batchlinks-webui
```

i tested most of it works (haven't tested Windows yet). If it's stable enough, i'll merge it with main. (I'll also ask some of my friend on discord to test it too i think)😊

That sd_filer thing is also pretty cool and convenient!

**Comment by etherealxx** [comment]
Update is now [live](https://github.com/etherealxx/batchlinks-webui#latest-release-v200)!🥳🎉
